More guided version of Exercise 3 for users to walk through
mitre/fhir-exercises pull request #11
Opened 2022-02-14 17:55 UTC by lmlevine

- Still have users doing the FHIR and API queries largely by themselves.
- For the python code a mix of 'fill in the blank' and helper function provided to ease difficulty
- for the ending I have line by line walkthroughs and then allow users to uncomment the code to run it
- Fixed API descriptions as well and linked to a better reference doc

2022-02-15 18:01 UTC, radamson requested changes
We now have a blank, guided and a solutions version of this exercise.
Should the blank exercise be deleted?

- [x] Update solution exercise
- [x] Move the completed version into the `Solutions` sub directory
- [ ] consisently refer to RxNorm Identifer Codes, including capitalization (I've seen `rxnorm codes`, `RxNofmr identifier code`, `rxcui code`)

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "From a clinical perspective, this exercise demonstrates the power of SMART-on-FHIR applications, where third-party data (in this case Drug on Drug interaction data), can be pulled in, paired wit
We never talk about SMART before this and SMART apps don't necessarily bring in third party data.

This either needs a better overview of SMART and the types of apps it makes possible or we shouldn't mention it.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "For this exercise we will call on the `MedicationRequest` which represents a medication prescription in FHIR.\n",
It would be nice to have a 📘 link to MedicationRequest here for future readers.

If you end up adding a link, then you'll also need to add a `Icons used in this guide` section at the top like the other exercises have.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +  },
The solutions version of this still has `verify=False` in the request unnecessarily.
![Screen Shot 2022-02-15 at 12 04 10 PM](https://user-images.githubusercontent.com/41651655/154111818-9e2cd4bb-9aba-4ed2-b4de-c5a63c619794.png)

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "As a first step let's leverage the list mapping lambda function we deployed in Exercise 1 to map out our JSON file (entering the entire bundle, and mapping by resource) \n",
It's not clear to me what you're asking for. I think this should explicitly say something like:

`Create a python list which contains only the `Bundle.entry.resource` elements from the bundle returned in the previous step`

This could also be tricky for attendees to implement. Can you provide a link here to how its done in previous exercises so they know where to look?

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "As a sanity test let's return the first resource item (index 0 or [0]) so we can get a better look at what information we have to work with."
IMO `prescriptions[0]` should already be prefilled in the code block below.

Later code blocks that are prefilled depend on this variable being named `prescriptions` so students need to know that they must name it that too.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "Based on our previous exercises we know we can use the `json_normalize` function parse the JSON into a pandas dataframe. Let's do that now and then output the resulting dataframe to confirm we'v
Combine these into a single markdown block (it makes it easier to double click and edit later).

Add a link to how json_normalize is used in the previous exercise.

Should there be any guidance on the `max_level` to use?

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +  },
Should `pd.set_option('display.max_columns', None)` and `df_prescriptions.head()` be prefilled? There's nothing in the instructions saying they should use those.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "While we will pause our work on the dataframe for the moment, it may be worth pausing to document our current set of available features and their potential utility.\n",
What are you expecting to be done here: `worth pausing to document our current set of available features and their potential utility.`

It doesn't look like the solutions file writes anything out for this.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "So we now have a basic datafame with drug and patient information. Before we can begin trying to construct a parser, we need to examine our Drug Interaction API to see how data is submitted and
Parser for what?

I think this should be something like `Let's examine the drug interaction api to see what data we'll need to extract from our dataframe`.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "Reviewing the NIH's RXNav database documentation. Link here: https://lhncbc.nlm.nih.gov/RxNav/APIs/index.html\n",
```suggestion
    "Review the NIH's RXNav API documentation: https://lhncbc.nlm.nih.gov/RxNav/APIs/index.html\n",
```

API documentation, not database documentation

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "We see one clear option we have to use is the RX CUI code using the six-digit RxNorm identifier code\n",
![Screen Shot 2022-02-15 at 12 18 34 PM](https://user-images.githubusercontent.com/41651655/154114524-22220183-0d0a-4369-9674-c433e05c627c.png)

Solution file is still using incorrect language here.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "We see one clear option we have to use is the RX CUI code using the six-digit RxNorm identifier code\n",
I'm not sure I'd call this the `one clear option`.

```suggestion
    "We see one clear option we have to use is the RxNorm identifier using the six-digit RxNorm identifier code\n",
```

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "https://lhncbc.nlm.nih.gov/RxNav/APIs/api-Interaction.findDrugInteractions.html\n",
This is linking to the wrong API. `findInteractionsFromList` is used in this exercise, not `findDrugInteractions`

```suggestion
    "https://lhncbc.nlm.nih.gov/RxNav/APIs/api-Interaction.findInteractionsFromList.html\n",
```

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "This correllates with our Patient data column: `resource.medicationCodeableConcept.coding.codes` (quite a mouthful! But we'll deal with that shortly).\n",
There is no "Patient data column"

```suggestion
    "This correlates with our `resource.medicationCodeableConcept.coding` data column: 
```

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "URL/list.json?rxcuis=[code 1]+[code 2]\n",
Would be nice to have this pattern formatted like we do in exercise 0.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    " - The URL is: https://rxnav.nlm.nih.gov/REST/interaction/\n",
Why not just include the URL above?

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +  },
This makes it seem like both combinations should be included in this code block.

I think more of this code block should be prefilled, especially since they need to add `headers={'accept': 'application/json'}` and that's not mentioned anywhere.

IMO this should be:

```python
# Fill out URL
url = ''
response = s.get(url, headers={'accept': 'application/json'})
response.json()
```

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "Taking stock, we have successfully accessed the Drug API, and hopefully now have an understanding of what the API returns when there is a drug interaction versus when there isn't.\n",
There should be more description about what we're actually seeing returned from the API.

Why are the rxcuis in the in interactionPair different that what we sent? Do we need to care about severity? What other elements could be present and where are the descriptions indicating what each element represents (hint should we be looking back at the API docs to interpret?)

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "First, we have a structured target to work toward for submitting our patient data to the Drug API. For each patient, we will need to compile a list of RXNorm codes of the prescriptions they are
the parameters are space-separated which gets encoded into either `+` or `%20`.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "pd.DataFrame([codings['code'] for MedicationRequest in prescriptions for codings in MedicationRequest['medicationCodeableConcept']['coding']]).head()"
This list comprehension filtered for codeabableconcepts where system=http://www.nlm.nih.gov/research/umls/rxnorm like is done in the following codeblock

`if coding['system'] == 'http://www.nlm.nih.gov/research/umls/rxnorm')...`

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "If we look back at our `df_prescriptions` DataFrame we can see that we already have a column for `medicationCodeableConcept.coding`. Let's take a similar approach to what we did in exercise 2 to
Attendees were never told to assign their dataframe to the `df_prescriptions` variable.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "Depending on how you've parsed it, certain fields are immediately usable in their current form. For others, we're going to need to do further work to parse out the precise information we want to
Are we expecting attendees to have parsed it differently? Are we going to run into issues later if they do?

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "Conduct a value count to confirm that only active prescriptions remain."
A link to a previous exercise or relevant pandas API documentation on the method to be used would be good here or this should be prefilled (I double attendees will remember the method to call)

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "We want to ensure that we're only querying active prescriptions. If a patient is no longer taking a drug, the risk of a Drug-on-Drug interaction is no longer applicable. If any inactive prescrip
It would be worth mentioning that a more complex analysis might also take `MedicationRequest.dispenseRequest.initialFill`, `MedicationRequest.dispenseRequest.dispenseInterval`, and ``MedicationRequest.dispenseRequest.validityPeriod` into account since an `active` medication may also define a MedicationRequest for the future which has yet to be prescribed and some medications may not be taken concurrently.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "#groups_by_patient = rx_df.groupby('insert your patient reference', sort=False)['insert your code column here'].apply(lambda x: x.values.tolist())"
`groups_by_patient.head()` should be prefilled here.

Is there really enough guidance here to help attendees complete this? Have they used `groupby` before or can we include a link to the pandas API docs?

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "        response_json = json.loads(response)\n",
this should be `response.json()` since we use that everywhere else.

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "print('Total number of possible drug interactions in patient cohort: ', count_drug_int)"
I would love to see a solution here that uses `apply` (e.g. Exercise 1 getting ATC codes) or `map` (e.g. Exercise 2 getting race and ethnicity) like we do in Exercise 1 & 2 that really makes use of the DataFrame and would be a lot cleaner. `.apply` & `.map` are also shown off earlier in this exercise with `get_rx_norm_code`

2022-02-15 18:01 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "    #print('For',rx_df['subject.reference'][patient_index])\n",
Why revert to using `rx_df` here when we created `groups_by_patients` specifically for processing this?

2022-02-18 06:17 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "From a clinical perspective, this exercise demonstrates the power of SMART-on-FHIR applications, where third-party data (in this case Drug on Drug interaction data), can be pulled in, paired wit
Removed SMART References. Agreed it's unnecessary in this context.

2022-02-18 06:22 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "For this exercise we will call on the `MedicationRequest` which represents a medication prescription in FHIR.\n",
Done!

2022-02-18 06:24 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +  },
Fixed.

2022-02-18 06:37 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "As a first step let's leverage the list mapping lambda function we deployed in Exercise 1 to map out our JSON file (entering the entire bundle, and mapping by resource) \n",
Not sure if I'm linking to the right link, but I did reference and point to our repo exercise 2 (where the most direct example of it exists) and cleaned up the language.

2022-02-18 06:39 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "As a sanity test let's return the first resource item (index 0 or [0]) so we can get a better look at what information we have to work with."
Good catch, I'll also leave it as the variable to be assigned in the line above to limit confusion

2022-02-18 06:54 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "Based on our previous exercises we know we can use the `json_normalize` function parse the JSON into a pandas dataframe. Let's do that now and then output the resulting dataframe to confirm we'v
Done! Added a bit on Max-level as well

2022-02-18 06:57 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +  },
Agreed. That does make it much more intuitive.

2022-02-18 07:01 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "While we will pause our work on the dataframe for the moment, it may be worth pausing to document our current set of available features and their potential utility.\n",
Tweaked the language on this. I don't think there's any real utility in doing anything further at this point (e.g., info() or describe()), beyond just eyeballing the sample output with head() so I modified the language to reflect that.

2022-02-18 07:13 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "We see one clear option we have to use is the RX CUI code using the six-digit RxNorm identifier code\n",
Good catch

2022-02-18 07:14 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "https://lhncbc.nlm.nih.gov/RxNav/APIs/api-Interaction.findDrugInteractions.html\n",
Swapped!

2022-02-18 07:18 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    " - The URL is: https://rxnav.nlm.nih.gov/REST/interaction/\n",
Good point!

2022-02-18 07:20 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "URL/list.json?rxcuis=[code 1]+[code 2]\n",
So I think simplifying it by just including the url eliminates the need for more complex formatting like exercise 0 but let me know what you think!

2022-02-18 07:23 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +  },
Done!

2022-02-18 07:37 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "Taking stock, we have successfully accessed the Drug API, and hopefully now have an understanding of what the API returns when there is a drug interaction versus when there isn't.\n",
agreed that that dialog is worth including.

2022-02-18 07:37 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "First, we have a structured target to work toward for submitting our patient data to the Drug API. For each patient, we will need to compile a list of RXNorm codes of the prescriptions they are
Done!

2022-02-18 07:43 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "pd.DataFrame([codings['code'] for MedicationRequest in prescriptions for codings in MedicationRequest['medicationCodeableConcept']['coding']]).head()"
I'm a little lost on this comment (sorry!)

2022-02-18 07:44 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "If we look back at our `df_prescriptions` DataFrame we can see that we already have a column for `medicationCodeableConcept.coding`. Let's take a similar approach to what we did in exercise 2 to
With the revised filler code inserted above they now are so the text is logical.

2022-02-18 07:47 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "Depending on how you've parsed it, certain fields are immediately usable in their current form. For others, we're going to need to do further work to parse out the precise information we want to
I don't anticipate any differences but this language is more as a catchall. Depending on your comfort, we can modify it.

2022-02-18 08:08 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "Conduct a value count to confirm that only active prescriptions remain."
I think since you're just calling the function directly on the column it should be alright to have them do it themselves, however you're right that the documentation will be helpful so editing it to include.

2022-02-18 08:12 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "We want to ensure that we're only querying active prescriptions. If a patient is no longer taking a drug, the risk of a Drug-on-Drug interaction is no longer applicable. If any inactive prescrip
Done!

2022-02-18 08:17 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "#groups_by_patient = rx_df.groupby('insert your patient reference', sort=False)['insert your code column here'].apply(lambda x: x.values.tolist())"
Added documentation and also provided code where they simply have to insert their column references to run it

2022-02-18 08:28 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "        response_json = json.loads(response)\n",
Done!

2022-02-18 08:40 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "    #print('For',rx_df['subject.reference'][patient_index])\n",
This was a workaround on my part. I tried using the groups_by_patient but the index reference just returned the list of drugs, not the grouped by ID. There's probably a better way to do it, but the workaround I found was to reference the original data frame. Maybe you have a recommendation for how to approach?

2022-02-18 08:40 UTC, lmlevine commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "print('Total number of possible drug interactions in patient cohort: ', count_drug_int)"
Still working on this one! Haven't gotten an alternative version working adequately yet, but I will continue on it.

2022-02-18 08:45 UTC, lmlevine commented
Resolved all in-text comments. There are a few items I left unresolved for you to review. 

I'm still working on seeing if I can redo the last bit to bring it in line with the previous exercises, but haven't gotten an alternative working adequately.

2022-02-18 20:12 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "pd.DataFrame([codings['code'] for MedicationRequest in prescriptions for codings in MedicationRequest['medicationCodeableConcept']['coding']]).head()"
Sorry, I meant `This list comprehension _should_ filter for codeableableconcepts...`

2022-02-18 21:03 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "pd.DataFrame([codings['code'] for MedicationRequest in prescriptions for codings in MedicationRequest['medicationCodeableConcept']['coding']]).head()"
Fixed in https://github.com/mitre/fhir-exercises/pull/11/commits/b51af37e6830747725c863f4bd8bb52e62418791

2022-02-18 21:03 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "print('Total number of possible drug interactions in patient cohort: ', count_drug_int)"
Updated in https://github.com/mitre/fhir-exercises/pull/11/commits/eaa1751428f9ad7dc246b207543a62dfbb558edb

2022-02-18 21:03 UTC, radamson commented on Exercise_3_DrugInteractions-Guided.ipynb
> +    "    #print('For',rx_df['subject.reference'][patient_index])\n",
Updated in https://github.com/mitre/fhir-exercises/pull/11/commits/eaa1751428f9ad7dc246b207543a62dfbb558edb

2022-02-18 21:13 UTC, radamson commented
@lmlevine I'm going to merge these changes into `main`. I still this needs another language sweep to tighten everything up and clean up some weird sentences (e.g. removing `effectively` from this sentence: `Test our original two drug combinations to ensure that it is effectively outputting the expected responses.`)

Things to look for:
* Comprehensive and descriptive text that makes it clear what's being asked.
* ✋ everywhere that the user needs to fill something in
* Solution and fill-in-the-blank versions are both up to date
* Solution for "bonus points" in `get_rx_norm_code` method

2022-02-18 21:27 UTC, merged